ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_AFL_LOOP, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_AFL_INIT, 0, 0, IS_VOID, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_AFL_COVERAGE_ON, 0, 0, IS_VOID, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_AFL_COVERAGE_OFF, 0, 0, IS_VOID, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_AFL_test_one_arg_fuzz, 0, 0, IS_VOID, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_AFL_test_three_arg_fuzz, 0, 0, IS_VOID, 0)
ZEND_END_ARG_INFO()

ZEND_FUNCTION(AFL_LOOP);
ZEND_FUNCTION(AFL_INIT);
ZEND_FUNCTION(AFL_COVERAGE_ON);
ZEND_FUNCTION(AFL_COVERAGE_OFF);
ZEND_FUNCTION(test_one_arg_fuzz);
ZEND_FUNCTION(test_three_arg_fuzz);

static const zend_function_entry ext_functions[] = {
	ZEND_FE(AFL_LOOP, arginfo_AFL_LOOP)
	ZEND_FE(AFL_INIT, arginfo_AFL_INIT)
	ZEND_FE(AFL_COVERAGE_ON, arginfo_AFL_COVERAGE_ON)
	ZEND_FE(AFL_COVERAGE_OFF, arginfo_AFL_COVERAGE_OFF)
	ZEND_FE(test_one_arg_fuzz, arginfo_AFL_test_one_arg_fuzz)
	ZEND_FE(test_three_arg_fuzz, arginfo_AFL_test_three_arg_fuzz)
	ZEND_FE_END
};
